package com.xworkz.xworkmodule.entity;

import lombok.Data;
import lombok.RequiredArgsConstructor;

import javax.persistence.*;
import java.security.SecureRandom;

@Entity
@Table(name = "module_table")
@Data
@RequiredArgsConstructor
@NamedQuery(name = "findNameThroughLogin",query = "select e.name from ModuleEntity e where e.email =:email and e.autoGeneratedPassword =:pass")
@NamedQuery(name = "countEmail",query = "select count(e) from ModuleEntity e where e.email=:SetEmail")
@NamedQuery(name="countName" , query ="select count(e) from ModuleEntity e where e.name =:SetName")
@NamedQuery(name = "countAltEmail", query = "select count(e) from ModuleEntity e where e.alterEmail = :SetAltEmail")
@NamedQuery(name = "countPhone",query = "select count(e) from ModuleEntity e where e.phNo=:setPhone")
@NamedQuery(name = "countAltPhNo",query = "select count(e) from ModuleEntity e where e.alterPhNo=:setAltPhNo")
public class ModuleEntity {

    @Id
    private int id;
    private String name;
    private String email;
    private String alterEmail;
    private double phNo;
    private double alterPhNo;
    private String location;
    @Column(name = "password_generated")
    private char[] autoGeneratedPassword;
    private int login_count;


}