package com.xworkz.xworkmodule.entity;

import lombok.Data;
import lombok.RequiredArgsConstructor;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.security.SecureRandom;

@Entity
@Table(name = "module_table")
@Data
@RequiredArgsConstructor
public class ModuleEntity {

    @Id
    private int id;
    private String name;
    private String email;
    private String alterEmail;
    private double phNo;
    private double alterPhNo;
    private String location;
    @Column(name = "password_generated")
    private char[] autoGeneratedPassword;


}