package com.xworkz.xworkmodule.entity;

import lombok.Data;
import lombok.RequiredArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@Table(name = "module_table")
@Data
@RequiredArgsConstructor
@NamedQuery(name = "findNameThroughLogin",query = "select e.name from ModuleEntity e where e.email =:email and e.autoGeneratedPassword =:pass")
@NamedQuery(name = "countEmail",query = "select count(e) from ModuleEntity e where e.email=:SetEmail")
@NamedQuery(name="countName" , query ="select count(e) from ModuleEntity e where e.name =:SetName")
@NamedQuery(name = "countAltEmail", query = "select count(e) from ModuleEntity e where e.alterEmail = :SetAltEmail")
@NamedQuery(name = "countPhone",query = "select count(e) from ModuleEntity e where e.phNo=:setPhone")
@NamedQuery(name = "countAltPhNo",query = "select count(e) from ModuleEntity e where e.alterPhNo=:setAltPhNo")
@NamedQuery(name = "getEntityByEmail",query = "select e from ModuleEntity e where e.email=:setEmail")
@NamedQuery(name = "getDataByEmail",query = "select e from ModuleEntity e where e.email = :byEmail")
@NamedQuery(name="updateDetailsByName",query = "UPDATE ModuleEntity e SET e.phNo=:phNo, e.alterEmail=:alterEmail, e.alterPhNo=:alterPhNo,e.email=:email,e.location=:location where e.name=:name")
@NamedQuery(name = "resetPasswordAndLoginCount",query = "update ModuleEntity e set e.autoGeneratedPassword=:newPassword, e.login_count =:loginCount, e.accountLocked=:accountLocked where e.email=:email")
public class ModuleEntity extends AbstractAuditEntity{
    @Id
    private int id;
    private String name;
    private String email;
    private String alterEmail;
    private double phNo;
    private double alterPhNo;
    private String location;
    @Column(name = "password_generated")
    private String autoGeneratedPassword;
    private Integer login_count=-1;
    @Column(name = "account_locked")
    private boolean accountLocked;



}