package com.xworkz.xworkmodule.service;

import com.xworkz.xworkmodule.dto.ModuleDto;
import com.xworkz.xworkmodule.entity.ModuleEntity;

public interface ModuleService {

    boolean Validate(ModuleDto dto);

    String getName(String email, char[] password);
    Long countName(String name);
    Long countByEmail(String email);
    Long countByAltEmail(String altEmail);
    Long countByPhone(String phone);
    Long countByAltPhone(String altPhone);
    boolean updatePassword(char[] autoGeneratedPassword, char[] newPassword, char[] confirmPassword);


}
