package com.xworkz.xworkmodule.controller;


import com.xworkz.xworkmodule.entity.ModuleEntity;
import com.xworkz.xworkmodule.repository.ModuleRepo;
import com.xworkz.xworkmodule.service.ModuleService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class UpdatePasswordController {

    @Autowired
    private ModuleService service;
    ModuleEntity entity = new ModuleEntity();



    @PostMapping("/update")
    public String updatePassword(@RequestParam char[] autoGeneratedPassword, @RequestParam char[] newPassword, @RequestParam char[] confirmPassword) {


        if(!(newPassword == confirmPassword))
        {
            System.out.println("new password and confirm password are not same");
        }
        boolean up =service.updatePassword(autoGeneratedPassword,newPassword,confirmPassword);

            return "Login.jsp";


    }
}
